name: Python Build

on:
  push:
    branches:
      - "**"

env:
  PYTHON_ENV: "PROD"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Python app for 5 seconds
        run: python app.py # Replace "your_script.py" with the name of your Python script or application
        timeout-minutes: 1 # Timeout after 1 minute (adjust if needed)
